src/blog/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from . import views
from .feeds import LatestEntriesFeed
from .sitemap import (
    PostSitemap, TagSitemap,
    CategorySitemap, StaticSitemap
)

app_name = 'blog'

sitemaps = {
    'post': PostSitemap,
    'category': CategorySitemap,
    'tag': TagSitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),

    path('ping/', views.ping, name='ping'),

    path('alltag/', views.TagListView.as_view(), name='tag_list'),

    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),

    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),

    path('tag/<str:tag>/', views.TagView.as_view(), name='tag'),

    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='comment'),
    path('recomment/<int:pk>/', views.ReCommentCreateView.as_view(), name='recomment'),
    path('file_download/<int:pk>/', views.file_download, name='file_download'),


    path('private/', views.PostPrivateIndexView.as_view(), name='private'),

    path('latest/feed/', LatestEntriesFeed(), name='feed'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

src/mysite/urls.py
from django.conf import settings #add
from django.contrib import admin
from django.urls import path, include #add
from django.conf.urls.static import static #add
from django.contrib.staticfiles.urls import staticfiles_urlpatterns #add

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')), #add
]

urlpatterns += staticfiles_urlpatterns() #add
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #add
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #add

admin.site.site_header = "Huutrinh's Site Admin"
admin.site.site_title = "Huutrinh's Site Admin Portal"
admin.site.index_title = "Welcome to Huutrinh's Site Portal"

src/blog/models.py
import os
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.db import models
from django.utils import timezone
from markdown import markdown
from django.utils.html import mark_safe


# Choose color for site
SITE_COLORS = (
    ('primary', '青色'),
    ('secondary', '灰色'),
    ('success', '緑色'),
    ('info', '水色'),
    ('warning', '黄色'),
    ('danger', '赤'),
    ('dark', '黒'),
)

DEFAULT_HEADER_TEXT = """\
Ký Sự Nhật Bản
"""
#[filter url]https://www.linkedin.com/in/trinh-nguyen-huu-8b6079104/<split>Hồ sơ Linkedin[end]\

class Category(models.Model):
    """Category"""
    name = models.CharField('CategoryName', max_length=255)

    def __str__(self):
        """str."""
        return self.name


class Tag(models.Model):
    """Tag"""
    name = models.CharField('TagName', max_length=255)

    def __str__(self):
        """str."""
        return self.name


class Post(models.Model):
    """Article"""
    title = models.CharField('Title', max_length=255)
    text = models.TextField('Body')
    category = models.ForeignKey(
        Category, verbose_name='Category', on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='Tag')
    thumnail = models.ImageField(
        'Thumbnail', upload_to='post_thumbnail/%Y/%m/%d/', blank=True, null=True)
    is_publick = models.BooleanField('Publicable?', default=True)
    friend_posts = models.ManyToManyField(
        'self', verbose_name='RelatedArticle', blank=True)
    description = models.TextField('Description', blank=True)
    files = GenericRelation('File')
    created_at = models.DateTimeField('CreatedDate', default=timezone.now)

    def __str__(self):
        return self.title

    def get_description(self):
        if self.description:
            return self.description
        else:
            description = 'Category:{0} Tag:{1}'
            category = self.category
            tags = ' '.join(tag.name for tag in self.tag.all())
            description = description.format(category, tags)
            return description

    def get_next(self):
        """Get next article (datetime)

        Not good at performance
        """
        next_post = Post.objects.filter(
            is_publick=True, created_at__gt=self.created_at
        ).order_by('-created_at')
        if next_post:
            return next_post.last()
        return None

    def get_prev(self):
        """Get previous article (datetime)

        Not good at performance
        """
        prev_post = Post.objects.filter(
            is_publick=True, created_at__lt=self.created_at
        ).order_by('-created_at')
        if prev_post:
            return prev_post.first()
        return None

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.text, extensions=['fenced_code', 'attr_list'], safe_mode='escape'))

class Comment(models.Model):
    """Comment"""
    name = models.CharField('Name', max_length=255, default='UnName')
    text = models.TextField('Comment')
    icon = models.ImageField(
        'Thumbnail', upload_to='comment_thumbnail/%Y/%m/%d/', blank=True, null=True)
    target = models.ForeignKey(
        Post, on_delete=models.CASCADE, verbose_name='TargetArticle')
    files = GenericRelation('File')
    created_at = models.DateTimeField('CreatedDate', default=timezone.now)

    def __str__(self):
        return self.text[:10]

    def get_filename(self):
        """Get filename"""
        return os.path.basename(self.file.url)


class ReComment(models.Model):
    """Reply comment"""
    name = models.CharField('Name', max_length=255, default='UnName')
    text = models.TextField('Comment')
    icon = models.ImageField(
        'Thumbnail', upload_to='recomment_thumbnail/%Y/%m/%d//', blank=True, null=True)
    target = models.ForeignKey(
        Comment, on_delete=models.CASCADE, verbose_name='TargetArticle')
    files = GenericRelation('File')
    created_at = models.DateTimeField('CreatedDate', default=timezone.now)

    def __str__(self):
        return self.text[:10]

    def get_filename(self):
        """Get filename"""
        return os.path.basename(self.file.url)


class Link(models.Model):
    """Link"""
    name = models.CharField('LinkName', max_length=255)
    adrs = models.CharField('Address', max_length=255)

    def __str__(self):
        return self.name


class Analytics(models.Model):
    """Analytic information"""
    name = models.CharField('Analytic', max_length=255, blank=True)
    html = models.TextField('AnalyticHtml', blank=True)

    def __str__(self):
        return self.name


class Ads(models.Model):
    """AdsRelated"""
    name = models.CharField('AdsName', max_length=255, blank=True)
    html = models.TextField('AdsHtml', blank=True)

    def __str__(self):
        return self.name


class SiteDetail(models.Model):
    """Site detail information"""
    site = models.OneToOneField(Site, verbose_name='Site', on_delete=models.PROTECT)
    title = models.CharField('Title', max_length=255, default='Huutrinh\'s blog')
    header_text = models.TextField('HeaderText', max_length=255, default=DEFAULT_HEADER_TEXT)
    description = models.TextField('Description', max_length=255, default='Description')
    author = models.CharField('Author', max_length=255, default='Huutrinh')
    author_mail = models.EmailField('AuthorMail', max_length=255, default='trinhsp89@gmail.com')
    color = models.CharField('Color', choices=SITE_COLORS, default='primary', max_length=30)

    def __str__(self):
        return self.author


class PopularPost(models.Model):
    """Popular post"""
    title = models.CharField('Title', max_length=255)
    url = models.CharField('URL', max_length=255)
    page_view = models.IntegerField('PageView')

    def __str__(self):
        return '{0} - {1} - {2}'.format(
            self.url, self.title, self.page_view)


class Image(models.Model):
    """Image file related to article"""
    title = models.CharField('Title', max_length=255, blank=True)
    post = models.ForeignKey(
        Post, verbose_name='Article', on_delete=models.PROTECT,
    )
    src = models.ImageField('Image', upload_to='images/%Y/%m/%d/', help_text='Save after sending.')
    created_at = models.DateTimeField('CreatedDate', default=timezone.now)

    def __str__(self):
        return 'Indirect Link:[filter imgpk]{0}[end] Direct link:[filter img]{1}[end]'.format(self.pk, self.src.url)


class File(models.Model):
    """File related to article and comment"""
    title = models.CharField('Titile', max_length=255, blank=True)
    src = models.FileField('TempFile', upload_to='files/%Y/%m/%d/')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    created_at = models.DateTimeField('CreatedDate', default=timezone.now)

    def __str__(self):
        return 'Model:{} pk:{} url:{}'.format(self.content_type, self.object_id, self.src.url)

    def get_filename(self):
        """Get filename"""
        return os.path.basename(self.src.url)

src/blog/forms.py
from django import forms
from django.contrib.contenttypes.forms import generic_inlineformset_factory
from .models import Comment, ReComment, File
from .fields import SimpleCaptchaField


class PostSerachForm(forms.Form):
    """記事検索フォーム"""

    keyword = forms.CharField(
        label='keyword', required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control mr-sm-2', 'placeholder': 'Quick Search'}),
    )


class CommentCreateForm(forms.ModelForm):
    """コメント投稿フォーム"""

    captha = SimpleCaptchaField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = Comment
        fields = ('name', 'text', 'icon')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
            }),
            'text': forms.Textarea(attrs={
                'class': "form-control",
            }),
            'icon': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }


class ReCommentCreateForm(forms.ModelForm):
    """返信コメント投稿フォーム"""

    captha = SimpleCaptchaField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = ReComment
        fields = ('name', 'text', 'icon')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
            }),
            'text': forms.Textarea(attrs={
                'class': "form-control",
            }),
            'icon': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }


FileInlineFormSet = generic_inlineformset_factory(
    File, fields=('src',), can_delete=False, extra=1,
)

src/blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sitemaps import ping_google
from django.urls import reverse_lazy
from django.db.models import Q, Count
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.views import generic
from .forms import PostSerachForm, CommentCreateForm, ReCommentCreateForm, FileInlineFormSet
from .models import Post, Comment, Tag, Category, ReComment, File


class BaseListView(generic.ListView):
    """記事の一覧表示の基底クラス"""
    paginate_by = 10

    def get_queryset(self):
        """公開フラグがTrue、作成日順の記事を返す."""
        # post.categoryや、post.tag.allをテンプレートで書く場合は
        # それぞれselect_relatedやprefetch_relatedで改善できる場合があります。
        queryset = Post.objects.filter(
            is_publick=True).order_by('-created_at').select_related('category').prefetch_related('tag')
        return queryset


class PostIndexView(BaseListView):
    """トップページ、クイックサーチ"""

    def get_queryset(self):
        """クイックサーチの絞り込み"""
        global_form = PostSerachForm(self.request.GET)
        global_form.is_valid()
        keyword = global_form.cleaned_data['keyword']
        queryset = super().get_queryset()

        # 大文字小文字の区別なく、タイトル、本文に含むかのor検索
        if keyword:
            for word in keyword.split():
                queryset = queryset.filter(
                    Q(title__icontains=word) | Q(text__icontains=word))
        return queryset


class PostPrivateIndexView(LoginRequiredMixin, BaseListView):
    """非公開の記事一覧"""

    def get_queryset(self):
        """公開フラグがFalse、作成日順"""
        queryset = Post.objects.filter(
            is_publick=False).order_by('-created_at').select_related('category').prefetch_related('tag')
        return queryset


class CategoryView(BaseListView):
    """カテゴリのリンククリック"""

    def get_queryset(self):
        """カテゴリでの絞り込み"""
        category_name = self.kwargs['category']
        self.category = Category.objects.get(name=category_name)
        queryset = super().get_queryset().filter(category=self.category)
        return queryset

    def get_context_data(self, *args, **kwargs):
        """クリックされたカテゴリを保持"""
        context = super().get_context_data(*args, **kwargs)
        context['category'] = self.category
        return context


class TagView(BaseListView):
    """タグのリンククリック"""

    def get_queryset(self):
        """タグで絞り込み"""
        tag_name = self.kwargs['tag']
        self.tag = Tag.objects.get(name=tag_name)
        queryset = super().get_queryset().filter(tag=self.tag)
        return queryset

    def get_context_data(self, *args, **kwargs):
        """クリックされたタグを保持"""
        context = super().get_context_data(*args, **kwargs)
        context['tag'] = self.tag
        return context


class PostDetailView(generic.DetailView):
    """記事詳細ページ"""
    model = Post

    def get_object(self, queryset=None):
        """その記事が公開か、ユーザがログインしていればよし"""
        post = super().get_object()
        if post.is_publick or self.request.user.is_authenticated:
            return post
        else:
            raise Http404


class CommentCreateView(generic.CreateView):
    """コメント投稿画面

    '^comment/(?P<pk>[0-9]+)/$'のようにして、記事のpkも受け取っている
    このpkをcontextへ渡し前へ戻るリンクに利用したり、targetに指定する記事を取得するのに使う

    """
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        """記事をコメントのtargetに指定"""
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.target = Post.objects.get(pk=post_pk)
        comment.save()
        formset = FileInlineFormSet(self.request.POST, instance=comment, files=self.request.FILES)
        if formset.is_valid():
            formset.save()
        return redirect('blog:detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        if 'formset' not in context:
            context['formset'] = FileInlineFormSet(self.request.POST or None)
        return context



class ReCommentCreateView(generic.CreateView):
    """返信コメント投稿"""

    model = ReComment
    form_class = ReCommentCreateForm
    template_name = 'blog/comment_form.html'

    def form_valid(self, form):
        """記事をコメントのtargetに指定"""
        comment_pk = self.kwargs['pk']
        comment = Comment.objects.get(pk=comment_pk)
        recomment = form.save(commit=False)
        recomment.target = comment
        recomment.save()

        formset = FileInlineFormSet(self.request.POST, instance=recomment, files=self.request.FILES)
        if formset.is_valid():
            formset.save()
        return redirect('blog:detail', pk=comment.target.pk)

    def get_context_data(self, **kwargs):
        comment_pk = self.kwargs['pk']
        comment = Comment.objects.get(pk=comment_pk)
        context = super().get_context_data(**kwargs)
        context['post'] = comment.target
        if 'formset' not in context:
            context['formset'] = FileInlineFormSet(self.request.POST or None)
        return context


class TagListView(generic.ListView):
    """タグの一覧ビュー"""

    model = Tag
    queryset = Tag.objects.annotate(
        num_posts=Count('post')).order_by('-num_posts')


@login_required
def ping(request):
    """Googleへpingを送信する"""
    try:
        url = reverse_lazy('blog:sitemap')
        ping_google(sitemap_url=url)
    except Exception:
        raise
    else:
        return redirect('blog:index', permanent=True)


def file_download(request, pk):
    """コメントに添付されたファイルのダウンロード

    ユーザーがアップロードできるファイルなので、セキュリティ対策のため
    必ずブラウザ上で開かせず、ダウンロードさせるようにする
    """
    file = get_object_or_404(File, pk=pk)
    response = HttpResponse(file.src, content_type='application/octet-stream')
    response['Content-Disposition'] = 'attachment; filename="{}"'.format(file.get_filename())
    return response

src/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>

    <meta charset="utf-8">
    <meta name="keywords" content="{% block meta_key %}{% endblock %}">
    <meta name="description" content="{% block meta_des %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block icon %}<link rel="shortcut icon" href="{% static 'blog/img/favicon.ico' %}">{% endblock %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'blog/css/base.css'  %}">

    {% block extracss %}{% endblock %}

  </head>
  <body>
    {% block layout %}{% endblock %}

  <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.js"></script>
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.8/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script>
        $(function() {
            $("img.lazy").lazyload({
                threshold:200,
                effect:"fadeIn",
                effect_speed:3000,
            });
        });
    </script>

  <!-- Custom JS -->
  {% block extrajs %}{% endblock %}

  {% block analytics %}
    <!-- アナリティクス -->
      {% for anal in analytics %}
        {{ anal.html | safe }}
      {% endfor %}
    <!-- アナリティクス終わり -->
  {% endblock %}
  
  </body>
</html>

src/blog/templates/blog/comment_form.html
{% extends "blog/main_layout.html" %}
{% load static %}
{% load blogfilter %}
{% block meta_des %}Trang comment - {{ mysite.title }}{% endblock %}
{% block title %}Trang comment - {{ mysite.title }}{% endblock %}

{% block bread%}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">Bài viết mới</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blog:category' post.category.name %}">{{ post.category.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></li>
    <li class="breadcrumb-item">コメント</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
{{ form.non_field_errors }}
<form action="" method="POST" enctype='multipart/form-data'>
  {% for field in form %}
    <div class="form-group">
      {{ field.errors }}
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field }}
    </div>
  {% endfor %}<!-- コメント部分のフォーム終わり -->

  {{ formset.management_form }}
  {% for form in formset %}
    {{ form.id }}
    {{ form.non_field_errors }}
    {% for field in form.visible_fields %}
      <div class="form-group">
        {{ field.errors }}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
      </div>
    {% endfor %}<!-- 1つのファイルフォーム終わり -->

  {% endfor %}<!-- formset終了 -->
  {% csrf_token %}
  <button class="btn btn-{{ mysite.color }}" type="submit">Comment</button>
  <a class="btn btn-{{ mysite.color }}" href="{% url 'blog:detail' post.pk %}" rel="nofollow">Back</a>
</form>

{% endblock %}

src/blog/templates/blog/layout.html
{% extends 'blog/base.html' %}
{% block layout %}

<!-- グローバルナビゲーション -->
{% include 'blog/widgets/nav.html' %}

<!-- ヘッダー -->
{% include 'blog/widgets/header.html' %}

<!-- メインコンテンツ -->
{% block main %}
{% endblock %}

<!-- フッター -->
{% include 'blog/widgets/footer.html' %}

{% endblock %}

src/blog/templates/blog/main_layout.html
{% extends 'blog/layout.html' %}

{% block main %}
<div class="container">
   {% block bread %}{% endblock %}
  <div class="row">
    <!-- 左側のメインコンテンツ -->
    <main class="col-12 col-md-8">
      {% block content %}
      {% endblock %}
    </main><!-- メインコンテンツ終了 -->

    <!-- 右側のサイドバー -->
    <aside class="col-12 col-md-3 offset-md-1">
      <!-- カテゴリ一覧 -->
      {% include 'blog/widgets/side_category.html' %}

      <!-- タグ一覧 -->
      {% include 'blog/widgets/side_tag.html' %}

      <!-- リンク一覧 -->
      {% include 'blog/widgets/side_link.html' %}

       <!-- コメント一覧 -->
       {% include 'blog/widgets/side_comment.html' %}

      <!-- 広告一覧 -->  
      {% for ad in ads %}
        {{ ad.html | safe }}
      {% endfor %}<!-- 広告一覧終了 -->
    </aside><!-- /サイドバー終了 -->
  </div><!-- /.row -->

  <!-- 人気記事一覧 -->
  <aside>
    {% include 'blog/widgets/popular_post_list.html' %}
  </aside>
</div>
{% endblock %}

src/blog/templates/blog/post_detail.html
{% extends "blog/main_layout.html" %}
{% load static %}

{% block meta_des %}
  {{ post.get_description }}
{% endblock %}

{% block title %}{{post.title}} - {{ mysite.title }}{% endblock %}

{% block bread%}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">Bài viết mới</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blog:category' post.category.name %}">{{ post.category.name }}</a></li>
    <li class="breadcrumb-item">{{ post.title }}</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
<!-- 目次部分 -->
<div id="toc"></div>

<!-- 記事詳細部分 -->
<article>
  {% include 'blog/widgets/detail_card.html' %}
</article>

<!-- コメント一覧 -->
<div id="comment-area">
  {% for comment in post.comment_set.all %}
    {% include 'blog/widgets/detail_comment.html' %}
  {% endfor %}
</div>

<div class="text-center my-5">
  <a class="btn btn-{{ mysite.color }} btn-lg text-white" href="{% url 'blog:comment' post.pk %}" rel="nofollow">Đến trang comment</a>
</div>

{% endblock %}

{% block extrajs %}
<script src="{% static 'blog/js/toc.js' %}"></script>
{% endblock %}

src/blog/templates/blog/post_list.html
{% extends "blog/main_layout.html" %}

{% block meta_des %}
    {% if tag %}
      Kết quả tìm kiếm tags {{ tag.name }} của trang {{ mysite.title }}.
    {% elif category %}
      Kết quả tìm kiếm category {{ category.name }} của trang {{ mysite.title }}.
    {% else %}
        {{ mysite.description }}
    {% endif %}
{% endblock %}

{% block title %}
    {% if tag %}
        {{ tag.name }} | {{ mysite.title }}
    {% elif category %}
        {{ category.name }} | {{ mysite.title }}
    {% else %}
        {{ mysite.title }}
    {% endif %}
{% endblock %}

{% block bread %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">Bài viết mới.</a></li>
    {% if tag %}
        <li class="breadcrumb-item">{{ tag.name }}</li>
    {% elif category %}
        <li class="breadcrumb-item">{{ category.name }}</li>
    {% endif %}
  </ol>
</nav>
{% endblock %}

{% block content %}
  {% for post in post_list %}
    <article>
      {% include 'blog/widgets/list_card.html' %}
    </article>
  {% endfor %}
  {% include "blog/widgets/page.html" %}
{% endblock %}

src/blog/templates/blog/tag_list.html
{% extends "blog/main_layout.html" %}
{% load static %}
{% load blogfilter %}
{% block meta_des %}Tags của trang {{ mysite.title }}{% endblock %}
{% block title %}Tags | {{ mysite.title }}{% endblock %}

{% block bread%}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">Bài mới</a></li>
    <li class="breadcrumb-item">Tags</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
  {% for tag in tag_list %}
    <p><a href="{% url 'blog:tag' tag.name %}">{{ tag.name }}({{ tag.num_posts }})</a></p>
    <hr>
  {% endfor %}
{% endblock %}