src/blog/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from . import views
from .feeds import LatestEntriesFeed
from .sitemap import (
    PostSitemap, TagSitemap,
    CategorySitemap, StaticSitemap
)

app_name = 'blog'

sitemaps = {
    'post': PostSitemap,
    'category': CategorySitemap,
    'tag': TagSitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', views.PostIndexView.as_view(), name='index'),

    path('ping/', views.ping, name='ping'),

    path('alltag/', views.TagListView.as_view(), name='tag_list'),

    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='detail'),

    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),

    path('tag/<str:tag>/', views.TagView.as_view(), name='tag'),

    path('comment/<int:pk>/', views.CommentCreateView.as_view(), name='comment'),
    path('recomment/<int:pk>/', views.ReCommentCreateView.as_view(), name='recomment'),
    path('file_download/<int:pk>/', views.file_download, name='file_download'),


    path('private/', views.PostPrivateIndexView.as_view(), name='private'),

    path('latest/feed/', LatestEntriesFeed(), name='feed'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
]

src/mysite/urls.py
from django.conf import settings #add
from django.contrib import admin
from django.urls import path, include #add
from django.conf.urls.static import static #add
from django.contrib.staticfiles.urls import staticfiles_urlpatterns #add

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')), #add
]

urlpatterns += staticfiles_urlpatterns() #add
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #add
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #add

admin.site.site_header = "Huutrinh's Site Admin"
admin.site.site_title = "Huutrinh's Site Admin Portal"
admin.site.index_title = "Welcome to Huutrinh's Site Portal"

src/blog/models.py
import os
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site
from django.db import models
from django.utils import timezone
from markdown import markdown
from django.utils.html import mark_safe


# Choose color for site
SITE_COLORS = (
    ('primary', '青色'),
    ('secondary', '灰色'),
    ('success', '緑色'),
    ('info', '水色'),
    ('warning', '黄色'),
    ('danger', '赤'),
    ('dark', '黒'),
)

DEFAULT_HEADER_TEXT = """\
Ký Sự Nhật Bản
"""
#[filter url]https://www.linkedin.com/in/trinh-nguyen-huu-8b6079104/<split>Hồ sơ Linkedin[end]\

class Category(models.Model):
    """Category"""
    name = models.CharField('CategoryName', max_length=255)

    def __str__(self):
        """str."""
        return self.name


class Tag(models.Model):
    """Tag"""
    name = models.CharField('TagName', max_length=255)

    def __str__(self):
        """str."""
        return self.name


class Post(models.Model):
    """Article"""
    title = models.CharField('Title', max_length=255)
    text = models.TextField('Body')
    category = models.ForeignKey(
        Category, verbose_name='Category', on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag, blank=True, verbose_name='Tag')
    thumnail = models.ImageField(
        'Thumbnail', upload_to='post_thumbnail/%Y/%m/%d/', blank=True, null=True)
    is_publick = models.BooleanField('Publicable?', default=True)
    friend_posts = models.ManyToManyField(
        'self', verbose_name='RelatedArticle', blank=True)
    description = models.TextField('Description', blank=True)
    files = GenericRelation('File')
    created_at = models.DateTimeField('CreatedDate', default=timezone.now)

    def __str__(self):
        return self.title

    def get_description(self):
        if self.description:
            return self.description
        else:
            description = 'Category:{0} Tag:{1}'
            category = self.category
            tags = ' '.join(tag.name for tag in self.tag.all())
            description = description.format(category, tags)
            return description

    def get_next(self):
        """Get next article (datetime)

        Not good at performance
        """
        next_post = Post.objects.filter(
            is_publick=True, created_at__gt=self.created_at
        ).order_by('-created_at')
        if next_post:
            return next_post.last()
        return None

    def get_prev(self):
        """Get previous article (datetime)

        Not good at performance
        """
        prev_post = Post.objects.filter(
            is_publick=True, created_at__lt=self.created_at
        ).order_by('-created_at')
        if prev_post:
            return prev_post.first()
        return None

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.text, extensions=['fenced_code', 'attr_list'], safe_mode='escape'))

class Comment(models.Model):
    """Comment"""
    name = models.CharField('Name', max_length=255, default='UnName')
    text = models.TextField('Comment')
    icon = models.ImageField(
        'Thumbnail', upload_to='comment_thumbnail/%Y/%m/%d/', blank=True, null=True)
    target = models.ForeignKey(
        Post, on_delete=models.CASCADE, verbose_name='TargetArticle')
    files = GenericRelation('File')
    created_at = models.DateTimeField('CreatedDate', default=timezone.now)

    def __str__(self):
        return self.text[:10]

    def get_filename(self):
        """Get filename"""
        return os.path.basename(self.file.url)


class ReComment(models.Model):
    """Reply comment"""
    name = models.CharField('Name', max_length=255, default='UnName')
    text = models.TextField('Comment')
    icon = models.ImageField(
        'Thumbnail', upload_to='recomment_thumbnail/%Y/%m/%d//', blank=True, null=True)
    target = models.ForeignKey(
        Comment, on_delete=models.CASCADE, verbose_name='TargetArticle')
    files = GenericRelation('File')
    created_at = models.DateTimeField('CreatedDate', default=timezone.now)

    def __str__(self):
        return self.text[:10]

    def get_filename(self):
        """Get filename"""
        return os.path.basename(self.file.url)


class Link(models.Model):
    """Link"""
    name = models.CharField('LinkName', max_length=255)
    adrs = models.CharField('Address', max_length=255)

    def __str__(self):
        return self.name


class Analytics(models.Model):
    """Analytic information"""
    name = models.CharField('Analytic', max_length=255, blank=True)
    html = models.TextField('AnalyticHtml', blank=True)

    def __str__(self):
        return self.name


class Ads(models.Model):
    """AdsRelated"""
    name = models.CharField('AdsName', max_length=255, blank=True)
    html = models.TextField('AdsHtml', blank=True)

    def __str__(self):
        return self.name


class SiteDetail(models.Model):
    """Site detail information"""
    site = models.OneToOneField(Site, verbose_name='Site', on_delete=models.PROTECT)
    title = models.CharField('Title', max_length=255, default='Huutrinh\'s blog')
    header_text = models.TextField('HeaderText', max_length=255, default=DEFAULT_HEADER_TEXT)
    description = models.TextField('Description', max_length=255, default='Description')
    author = models.CharField('Author', max_length=255, default='Huutrinh')
    author_mail = models.EmailField('AuthorMail', max_length=255, default='trinhsp89@gmail.com')
    color = models.CharField('Color', choices=SITE_COLORS, default='primary', max_length=30)

    def __str__(self):
        return self.author


class PopularPost(models.Model):
    """Popular post"""
    title = models.CharField('Title', max_length=255)
    url = models.CharField('URL', max_length=255)
    page_view = models.IntegerField('PageView')

    def __str__(self):
        return '{0} - {1} - {2}'.format(
            self.url, self.title, self.page_view)


class Image(models.Model):
    """Image file related to article"""
    title = models.CharField('Title', max_length=255, blank=True)
    post = models.ForeignKey(
        Post, verbose_name='Article', on_delete=models.PROTECT,
    )
    src = models.ImageField('Image', upload_to='images/%Y/%m/%d/', help_text='Save after sending.')
    created_at = models.DateTimeField('CreatedDate', default=timezone.now)

    def __str__(self):
        return 'Indirect Link:[filter imgpk]{0}[end] Direct link:[filter img]{1}[end]'.format(self.pk, self.src.url)


class File(models.Model):
    """File related to article and comment"""
    title = models.CharField('Titile', max_length=255, blank=True)
    src = models.FileField('TempFile', upload_to='files/%Y/%m/%d/')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    created_at = models.DateTimeField('CreatedDate', default=timezone.now)

    def __str__(self):
        return 'Model:{} pk:{} url:{}'.format(self.content_type, self.object_id, self.src.url)

    def get_filename(self):
        """Get filename"""
        return os.path.basename(self.src.url)

src/blog/forms.py
from django import forms
from django.contrib.contenttypes.forms import generic_inlineformset_factory
from .models import Comment, ReComment, File
from .fields import SimpleCaptchaField


class PostSerachForm(forms.Form):
    """記事検索フォーム"""

    keyword = forms.CharField(
        label='keyword', required=False,
        widget=forms.TextInput(
            attrs={'class': 'form-control mr-sm-2', 'placeholder': 'Quick Search'}),
    )


class CommentCreateForm(forms.ModelForm):
    """コメント投稿フォーム"""

    captha = SimpleCaptchaField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = Comment
        fields = ('name', 'text', 'icon')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
            }),
            'text': forms.Textarea(attrs={
                'class': "form-control",
            }),
            'icon': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }


class ReCommentCreateForm(forms.ModelForm):
    """返信コメント投稿フォーム"""

    captha = SimpleCaptchaField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = ReComment
        fields = ('name', 'text', 'icon')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
            }),
            'text': forms.Textarea(attrs={
                'class': "form-control",
            }),
            'icon': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }


FileInlineFormSet = generic_inlineformset_factory(
    File, fields=('src',), can_delete=False, extra=1,
)

src/blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sitemaps import ping_google
from django.urls import reverse_lazy
from django.db.models import Q, Count
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.views import generic
from .forms import PostSerachForm, CommentCreateForm, ReCommentCreateForm, FileInlineFormSet
from .models import Post, Comment, Tag, Category, ReComment, File


class BaseListView(generic.ListView):
    """記事の一覧表示の基底クラス"""
    paginate_by = 10

    def get_queryset(self):
        """公開フラグがTrue、作成日順の記事を返す."""
        # post.categoryや、post.tag.allをテンプレートで書く場合は
        # それぞれselect_relatedやprefetch_relatedで改善できる場合があります。
        queryset = Post.objects.filter(
            is_publick=True).order_by('-created_at').select_related('category').prefetch_related('tag')
        return queryset


class PostIndexView(BaseListView):
    """トップページ、クイックサーチ"""

    def get_queryset(self):
        """クイックサーチの絞り込み"""
        global_form = PostSerachForm(self.request.GET)
        global_form.is_valid()
        keyword = global_form.cleaned_data['keyword']
        queryset = super().get_queryset()

        # 大文字小文字の区別なく、タイトル、本文に含むかのor検索
        if keyword:
            for word in keyword.split():
                queryset = queryset.filter(
                    Q(title__icontains=word) | Q(text__icontains=word))
        return queryset


class PostPrivateIndexView(LoginRequiredMixin, BaseListView):
    """非公開の記事一覧"""

    def get_queryset(self):
        """公開フラグがFalse、作成日順"""
        queryset = Post.objects.filter(
            is_publick=False).order_by('-created_at').select_related('category').prefetch_related('tag')
        return queryset


class CategoryView(BaseListView):
    """カテゴリのリンククリック"""

    def get_queryset(self):
        """カテゴリでの絞り込み"""
        category_name = self.kwargs['category']
        self.category = Category.objects.get(name=category_name)
        queryset = super().get_queryset().filter(category=self.category)
        return queryset

    def get_context_data(self, *args, **kwargs):
        """クリックされたカテゴリを保持"""
        context = super().get_context_data(*args, **kwargs)
        context['category'] = self.category
        return context


class TagView(BaseListView):
    """タグのリンククリック"""

    def get_queryset(self):
        """タグで絞り込み"""
        tag_name = self.kwargs['tag']
        self.tag = Tag.objects.get(name=tag_name)
        queryset = super().get_queryset().filter(tag=self.tag)
        return queryset

    def get_context_data(self, *args, **kwargs):
        """クリックされたタグを保持"""
        context = super().get_context_data(*args, **kwargs)
        context['tag'] = self.tag
        return context


class PostDetailView(generic.DetailView):
    """記事詳細ページ"""
    model = Post

    def get_object(self, queryset=None):
        """その記事が公開か、ユーザがログインしていればよし"""
        post = super().get_object()
        if post.is_publick or self.request.user.is_authenticated:
            return post
        else:
            raise Http404


class CommentCreateView(generic.CreateView):
    """コメント投稿画面

    '^comment/(?P<pk>[0-9]+)/$'のようにして、記事のpkも受け取っている
    このpkをcontextへ渡し前へ戻るリンクに利用したり、targetに指定する記事を取得するのに使う

    """
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        """記事をコメントのtargetに指定"""
        comment = form.save(commit=False)
        post_pk = self.kwargs['pk']
        comment.target = Post.objects.get(pk=post_pk)
        comment.save()
        formset = FileInlineFormSet(self.request.POST, instance=comment, files=self.request.FILES)
        if formset.is_valid():
            formset.save()
        return redirect('blog:detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        if 'formset' not in context:
            context['formset'] = FileInlineFormSet(self.request.POST or None)
        return context



class ReCommentCreateView(generic.CreateView):
    """返信コメント投稿"""

    model = ReComment
    form_class = ReCommentCreateForm
    template_name = 'blog/comment_form.html'

    def form_valid(self, form):
        """記事をコメントのtargetに指定"""
        comment_pk = self.kwargs['pk']
        comment = Comment.objects.get(pk=comment_pk)
        recomment = form.save(commit=False)
        recomment.target = comment
        recomment.save()

        formset = FileInlineFormSet(self.request.POST, instance=recomment, files=self.request.FILES)
        if formset.is_valid():
            formset.save()
        return redirect('blog:detail', pk=comment.target.pk)

    def get_context_data(self, **kwargs):
        comment_pk = self.kwargs['pk']
        comment = Comment.objects.get(pk=comment_pk)
        context = super().get_context_data(**kwargs)
        context['post'] = comment.target
        if 'formset' not in context:
            context['formset'] = FileInlineFormSet(self.request.POST or None)
        return context


class TagListView(generic.ListView):
    """タグの一覧ビュー"""

    model = Tag
    queryset = Tag.objects.annotate(
        num_posts=Count('post')).order_by('-num_posts')


@login_required
def ping(request):
    """Googleへpingを送信する"""
    try:
        url = reverse_lazy('blog:sitemap')
        ping_google(sitemap_url=url)
    except Exception:
        raise
    else:
        return redirect('blog:index', permanent=True)


def file_download(request, pk):
    """コメントに添付されたファイルのダウンロード

    ユーザーがアップロードできるファイルなので、セキュリティ対策のため
    必ずブラウザ上で開かせず、ダウンロードさせるようにする
    """
    file = get_object_or_404(File, pk=pk)
    response = HttpResponse(file.src, content_type='application/octet-stream')
    response['Content-Disposition'] = 'attachment; filename="{}"'.format(file.get_filename())
    return response

src/blog/templates/blog/widgets/detail_card.html
{% load blogfilter %}
{% load static %}
{% load mathjax %}
<style>
    pre.prettyprint {
      white-space: pre;
    }
    .prettyprint ol.linenums > li {
      list-style-type: decimal; 
    }
</style>
<div class="card">
  <div class="card-header bg-{{ mysite.color }}">
    <h1 class="card-title text-white">{{ post.title }}</h1>
  </div>
  
  <div class="card-body">
      <span class="badge badge-{{ mysite.color }} badge-pill">{% by_the_time post.created_at %}</span>
      <span class="badge badge-{{ mysite.color }} badge-pill">{{ post.created_at }}</span>
      <br>
  
      <span class="badge badge-{{ mysite.color }}">
        <a class="text-white" href="{% url 'blog:category' post.category.name %}">{{ post.category.name }}</a>
      </span>
      <br>
  
      {% for tag in post.tag.all %}
        <span class="badge badge-{{ mysite.color }}">
          <a class="text-white" href="{% url 'blog:tag' tag.name %}">{{ tag.name }}</a>
        </span>
      {% endfor %}
      <hr>
  
      {% if user.is_authenticated %}
        <a href="{% url 'admin:blog_post_change' post.pk %}">Đến màn hình quản lý</a>
        <hr>
      {% endif %}
    
    <!-- {{ post.text | linebreaksbr | blog }} -->
    {{ post.get_message_as_markdown | linebreaksbr | blog }}
    <!-- {{ post.get_message_as_markdown }} -->
    
  </div>
  
  <div class="card-footer">
    <p>File đính kèm</p>
    {% for file in post.files.all %}
      <a href="{% url 'blog:file_download' file.pk %}">{{ file.title }} - {{ file.get_filename }}</a><br>
    {% endfor %}
  
    <p>Bài viết liên quan</p>
    {% for post in post.friend_posts.all %}
      {% if post.is_publick %}
          <p><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></p>
      {% endif %}
    {% endfor %}    
  
  </div>
</div>
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?skin=desert"></script>

src/blog/templates/blog/widgets/detail_comment.html
{% load blogfilter %}
{% load static %}
<div class="row mt-3">
  <div class="col-md-2 d-none d-md-block">
    {% if comment.icon %}
      <img class="img-fluid lazy" data-original="{{ comment.icon.url }}">
    {% else %}
      <img class="img-fluid lazy" data-original="{% static 'blog/img/noimage.png' %}">
    {% endif %}
  </div>
  <div class="col-md-10">
      <h5>
        {{ comment.name }}
        <span class="badge badge-{{ mysite.color }} badge-pill">{% by_the_time comment.created_at %}</span>
        <span class="badge badge-{{ mysite.color }} badge-pill">{{ comment.created_at }}</span>
        <a href="{% url 'blog:recomment' comment.pk %}">Reply</a>
      </h5>
      {% for file in comment.files.all %}
        <a href="{% url 'blog:file_download' file.pk %}">Tải file xuống({{ file.get_filename }})</a><br>
      {% endfor %}
      {{ comment.text | linebreaksbr }}
      <!-- 返信コメント -->
      {% for recomment in comment.recomment_set.all %}
        <div class="row mt-3">
          <div class="col-md-2 d-none d-md-block">
            {% if recomment.icon %}
              <img class="img-fluid lazy" data-original="{{ recomment.icon.url }}">
            {% else %}
              <img class="img-fluid lazy" data-original="{% static 'blog/img/noimage.png' %}">
            {% endif %}
          </div>
          <div class="col-md-10">
              <h5>
                {{ recomment.name }}
                <span class="badge badge-{{ mysite.color }} badge-pill">{% by_the_time recomment.created_at %}</span>
                <span class="badge badge-{{ mysite.color }} badge-pill">{{ recomment.created_at }}</span>
              </h5>
              {% for file in recomment.files.all %}
                <a href="{% url 'blog:file_download' file.pk %}">Tải file xuống({{ file.get_filename }})</a><br>
              {% endfor %}
              {{ recomment.text | linebreaksbr }}
        
          </div>
        </div>
      {% endfor %}
      <!-- 返信コメントおわり -->
  </div>
</div>

src/blog/templates/blog/widgets/footer.html
<footer class="text-center bg-{{ mysite.color }}">
  <div class="container">
    <p class="text-white">Copyright {{ mysite.author }} All Rights Reserved.</p>
    <p><a href="mailto:{{ mysite.author_mail }}" rel="nofollow">{{ mysite.author_mail }}</a></p>
  </div>
</footer>

src/blog/templates/blog/widgets/header.html
{% load blogfilter %}
<header class="jumbotron">
  <div class="container">
    <h1>{{ mysite.title }}</h1>
    {{ mysite.header_text | linebreaksbr | blog }}
  </div>
</header>

src/blog/templates/blog/widgets/list_card.html
{% load blogfilter %}
{% load static %}

<div class="mb-5 card">

  <div class="card-header bg-{{ mysite.color }}">
    <h1 class="card-title text-white">{{ post.title }}</h1>
  </div><!-- card-header終了 -->
  
  <div class="card-body row">
    <!-- card-bodyの左側 -->
    <div class="col-xs-12 col-sm-6 text-center">
      {% if post.thumnail %}
        <a href="{{ post.thumnail.url }}" target="_blank" rel="nofollow"><img class="img-fluid lazy" data-original="{{ post.thumnail.url }}" alt="{{ post.title }}"></a>
      {% else %}
        <img class="img-fluid lazy" data-original="{% static 'blog/img/noimage.png' %}" alt="{{ post.title }}">
      {% endif %}
    </div><!-- card-bodyの左側終わり -->
  
    <!-- card-bodyの右側 -->
    <div class="col-xs-12 col-sm-6">
      <span class="badge badge-{{ mysite.color }} badge-pill">{% by_the_time post.created_at %}</span>
      <span class="badge badge-{{ mysite.color }} badge-pill">{{ post.created_at }}</span>
      <br>
  
      <span class="badge badge-{{ mysite.color }}">
        <a class="text-white" href="{% url 'blog:category' post.category.name %}">{{ post.category.name }}</a>
      </span>
      <br>
  
      {% for tag in post.tag.all %}
        <span class="badge badge-{{ mysite.color }}">
          <a class="text-white" href="{% url 'blog:tag' tag.name %}">{{ tag.name }}</a>
        </span>
      {% endfor %}
      <hr>
  
      <a class="btn btn-outline-{{ mysite.color }} btn-lg btn-block" href="{% url 'blog:detail' post.pk %}">Đọc tiếp</a>
      <br>
  
      {% if user.is_authenticated %}
        <a href="{% url 'admin:blog_post_change' post.pk %}">Đến màn hình quản lý</a>
      {% endif %}
    </div><!-- card-bodyの右側おわり -->
  
  </div><!-- card-body終了 -->

</div>

src/blog/templates/blog/widgets/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-{{ mysite.color }}">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:tag_list' %}">All Tag</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" target="_blank" href="{% url 'blog:feed' %}" rel="nofollow">Feed</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:private' %}" rel="nofollow">Private</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" target="_blank" href="{% url 'admin:index' %}" rel="nofollow">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:ping' %}" rel="nofollow">Ping</a>
        </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'blog:index' %}">
      {{ global_form.keyword }}
      <button class="btn my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

src/blog/templates/blog/widgets/page.html
{% load blogfilter %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' 1 %}" aria-label="Previous">
          &laquo;
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          &lsaquo;
        </a>
      </li>
    {% endif %}

    <li class="page-item disabled"><a class="page-link" href="#!">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          &rsaquo;
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.paginator.num_pages %}" aria-label="Next">
          &raquo;
        </a>
      </li>
    {% endif %}
  </ul>
</nav>

src/blog/templates/blog/widgets/popular_post_list.html
 {% if popular_post_list %}
<!-- 過去の人気記事一覧 -->
<div class="list-group my-5 col-12">
    <a href="#" class="list-group-item text-white bg-{{ mysite.color }}">
      Bài viết được xem nhiều nhất tuần.
    </a>
    {% for popular in popular_post_list %}
    <a class="list-group-item" href="{{ popular.url }}">
        {{ popular.title }} - {{ popular.page_view }}View
    </a>
    {% endfor %}
</div><!-- 過去の人気記事一覧終了 -->
{% endif %}

src/blog/templates/blog/widgets/side_category.html
<div class="list-group">
  <a href="#" class="list-group-item text-white bg-{{ mysite.color }}">
    All Category
  </a>
  {% for category in categories %}
  <a class="list-group-item" href="{% url 'blog:category' category.name %}">
    {{ category.name }}<span class="badge badge-{{ mysite.color }} badge-pill float-right text-white">{{ category.num_posts }}</span>
  </a>
  {% endfor %}
</div>

src/blog/templates/blog/widgets/side_comment.html
{% load blogfilter %}

<div class="hidden-sm-down list-group my-5">
  <a href="#" class="list-group-item text-white bg-{{ mysite.color }}">
    Comment
  </a>
  {% for comment in comments  %}
  <a class="list-group-item" href="{% url 'blog:detail' comment.target.pk %}#comment-area" rel="nofollow">
      {{ comment.name }}(Reply:{{ comment.num_recomments }})
      <span class="badge badge-{{ mysite.color }} badge-pill float-right text-white">{% by_the_time comment.created_at %}</span>
  </a>
  {% endfor %}    
</div> <!-- コメント一覧終了 -->

src/blog/templates/blog/widgets/side_link.html
<div class="list-group my-5">
  <a href="#" class="list-group-item text-white bg-{{ mysite.color }}">
    Link
  </a>
  {% for link in links  %}
  <a class="list-group-item" href="{{ link.adrs }}" target="_blank" rel="nofollow">
      {{ link.name }}
  </a>
  {% endfor %}
</div> <!-- リンク一覧終了 -->

src/blog/templates/blog/widgets/side_tag.html
<div class="list-group mt-5">
  <a href="#" class="list-group-item text-white bg-{{ mysite.color }}">
    Tag
  </a>
  {% for tag in tags  %}
  <a class="list-group-item" href="{% url 'blog:tag' tag.name %}">
      {{ tag.name }}<span class="badge badge-{{ mysite.color }} badge-pill float-right text-white">{{ tag.num_posts }}</span>
  </a>
  {% endfor %}
  <a href="{% url 'blog:tag_list' %}" class="list-group-item">
    >>> Xem tất cả tags.
  </a>
</div><!-- タグ一覧終了 -->